server:
  port: 8080
eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          searchPaths: config
          uri: https://github.com/hztangsheng/victroyrepository
          username: hztangsheng
          password: hztangsheng@qq.com
      label: master
  application:
    name: config-server
